// Main APge action types
export const SET_MANY_POKEMONS = "SET_MANY_POKEMONS";
export const SET_MAIN_PAGE_ERROR = "TOGGLE_MAIN_PAGE_ERROR";
export const REMOVE_MAIN_PAGE_ERROR = "REMOVE_MAIN_PAGE_ERROR";
export const TOGGLE_MAIN_PAGE_LOADING = "TOGGLE_MAIN_PAGE_LOADING";

export const SET_SINGLE_POKEMON = "SET_SINGLE_POKEMON";
export const SET_SINGLE_ERROR = "TOGGLE_SINGLE_ERROR";
export const REMOVE_SINGLE_ERROR = "REMOVE_SINGLE_ERROR";
export const TOGGLE_SINGLE_LOADING = "TOGGLE_SINGLE_LOADING";
