// Main APge action types
export const SET_MANY_POKEMONS = "SET_MANY_POKEMONS";
export const SET_MAIN_PAGE_ERROR = "TOGGLE_MAIN_PAGE_ERROR";
export const REMOVE_MAIN_PAGE_ERROR = "REMOVE_MAIN_PAGE_ERROR";
export const TOGGLE_MAIN_PAGE_LOADING = "TOGGLE_MAIN_PAGE_LOADING";
